### ISSUE TITLE
Move old releases off S3 bucket

### ISSUE THREAD

**Issue by awick** [arkime/arkime#2642]
- [x] do a backup
- [x] tests.pl uses resources stored in aws - move to github - #2695
- [x] U18 screwdriver saves to s3 - shutdown July 1
- [ ] EL7 screwdriver saves to s3 - shutdown Aug 1
- [x] NOTICE file - move to github release - #2706 
- [x] snfmin.tar.gz is used by easybutton - move to github - #2703
- [x] video - save, but remove
- [x] molochdata - moved to https://github.com/arkime/arkime-test-data/raw/main/molochdata.tar.zst

**Comment by awick** [comment]
not using anymore
