### ISSUE TITLE
nodejs 20 support

### ISSUE THREAD

**Issue by awick** [arkime/arkime#2662]
- [x] upgrade better-sqlite3 - #2665 
- [x] switch from fs-ext to fs.statfs (requires 18.15+) hurray!! - #2667 
- [x] remove nodejs version check from db.js - #2667
- [x] update package.json engine that we support it - #2667
- [x] update arkime.com and README that supported
- [x] decide when to start using and update easybutton to USE it, this can be later
