### ISSUE TITLE
Cont3xt Vue3 TODO

### ISSUE THREAD

**Issue by 31453** [arkime/arkime#2972]
- [x] less empty space everywhere
- [x] reduce size of buttons in navbar, make them fixed width, and change the colors
  - [x] Menu bar font!! Why is it ST A TS? Stone age?
  - [x] Also buttons top of cards, except for the tags trash can that went on a bad diet
- [x] better indication of a search input? (the link group search has the happy little mag glass)
- [x] the itype pulldown next to link group search is missing a icon
- [x] Settings -> Integration disabled checkboxes don't show up or work? (It looks like it wants to be a circle, what is wrong with a freaking checkbox!!!)
- [x] Settings -> Linkgroups role picking doesn't seem to show on/off (might be all role picking is broken)
- [x] Users tab shows up in navbar even when not an userAdmin
- [x] Users tab and Create new view checkboxes and role picking broken too
- [x] Users/Stats tab table sorting chevrons missing
- [x] Users tab result count looks like leaving room for icon its a pull down but doesn't show it, also pagination missing but maybe it shows up when needed?
- [x] Andy is not a fan of text boxes having the same background of whats around, example Settings -> Integration, maybe just old
- [x] Horizontal centering of text/x in colorful boxes is off. examples: displayed tags, Users tab "Roles (i)",  
- [x] History search bar help was more complete in old version "Search history by indicator, iType, or tags (case-sensitive)"
- [x] move away from font awesome
- [x] minimize bundle size
- [x] remove dev console misinformation
- [x] fix console warnings on startup
- [x] do we need `concurrently` lib?
- [x] missing Arkime logo
- [x] bulk queries are hideous
- [x] deployment error: `Refused to apply style from 'https://.../mdi-font/css/materialdesignicons.min.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

**Comment by 31453** [comment]
"maybe just old" 🤣

**Comment by 31453** [comment]
We don't need the `concurrently` library, but I do like it, so I'm keeping it. https://www.npmjs.com/package/concurrently

I tried running the `npm run cont3xt:dev` with `&` and not `concurrently`, and while it works, the `concurrently` output looks better and is easier to read.
